// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fTtVES61WzIhogy4sXIwp0pHnpAk4p0',
    appId: '1:763862308493:web:bcb6d8905ca0389ecaf4c4',
    messagingSenderId: '763862308493',
    projectId: 'inventory-app-12174',
    authDomain: 'inventory-app-12174.firebaseapp.com',
    storageBucket: 'inventory-app-12174.firebasestorage.app',
    measurementId: 'G-Q95RGFWF5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Ahy8Sv_ubv9latxsesAjt3hVwZ5eBWI',
    appId: '1:763862308493:android:79d8ec4596ed1c94caf4c4',
    messagingSenderId: '763862308493',
    projectId: 'inventory-app-12174',
    storageBucket: 'inventory-app-12174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRIEp8XQaNah7KQ-midwIGg0OrI79VAPE',
    appId: '1:763862308493:ios:8e178000cad52856caf4c4',
    messagingSenderId: '763862308493',
    projectId: 'inventory-app-12174',
    storageBucket: 'inventory-app-12174.firebasestorage.app',
    iosBundleId: 'com.example.stoxy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRIEp8XQaNah7KQ-midwIGg0OrI79VAPE',
    appId: '1:763862308493:ios:8e178000cad52856caf4c4',
    messagingSenderId: '763862308493',
    projectId: 'inventory-app-12174',
    storageBucket: 'inventory-app-12174.firebasestorage.app',
    iosBundleId: 'com.example.stoxy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fTtVES61WzIhogy4sXIwp0pHnpAk4p0',
    appId: '1:763862308493:web:b24029732780b4a3caf4c4',
    messagingSenderId: '763862308493',
    projectId: 'inventory-app-12174',
    authDomain: 'inventory-app-12174.firebaseapp.com',
    storageBucket: 'inventory-app-12174.firebasestorage.app',
    measurementId: 'G-XTJ41RSKG3',
  );

}