// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrwxu-KwUr3aPaoWgC5bCEIhcT18CyDBo',
    appId: '1:687535824647:web:4bcce1477f07e9ff442fa2',
    messagingSenderId: '687535824647',
    projectId: 'stoxy-928e8',
    authDomain: 'stoxy-928e8.firebaseapp.com',
    storageBucket: 'stoxy-928e8.firebasestorage.app',
    measurementId: 'G-LBF49X6TEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsSEe7TyAdtMexsGh6nyb2EbHlVFdkGGU',
    appId: '1:687535824647:android:11081cbbdedf56df442fa2',
    messagingSenderId: '687535824647',
    projectId: 'stoxy-928e8',
    storageBucket: 'stoxy-928e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohvQZXi_fDXNA_S1HtBvEOuNtqkh85eY',
    appId: '1:687535824647:ios:716d7ebcd8c7d922442fa2',
    messagingSenderId: '687535824647',
    projectId: 'stoxy-928e8',
    storageBucket: 'stoxy-928e8.firebasestorage.app',
    iosBundleId: 'com.example.stoxy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohvQZXi_fDXNA_S1HtBvEOuNtqkh85eY',
    appId: '1:687535824647:ios:716d7ebcd8c7d922442fa2',
    messagingSenderId: '687535824647',
    projectId: 'stoxy-928e8',
    storageBucket: 'stoxy-928e8.firebasestorage.app',
    iosBundleId: 'com.example.stoxy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrwxu-KwUr3aPaoWgC5bCEIhcT18CyDBo',
    appId: '1:687535824647:web:a45cd82540d08ed5442fa2',
    messagingSenderId: '687535824647',
    projectId: 'stoxy-928e8',
    authDomain: 'stoxy-928e8.firebaseapp.com',
    storageBucket: 'stoxy-928e8.firebasestorage.app',
    measurementId: 'G-R7ZHX7WMXL',
  );
}
